### ISSUE TITLE
Los estudiantes deberán armar una única planilla por comisión para comenzar a anotarse. Luego lo informarán a través de un formulario de Google.

### ISSUE THREAD

**Issue by cristiangavilan** [Grupo-7-Pythonisa/final-project#2]

**Comment by cristiangavilan** [comment]
Formulario con la conformacion del grupo entregado por  @marianom123  en el dia de la fecha

**Comment by marianom123** [comment]
Se envió el formulario. Adjunto imagen.
![Imagen de WhatsApp 2024-03-25 a las 18 20 38_78f1bc39](https://github.com/Grupo-7-Pythonisa/final-project/assets/45110180/34dab029-d7e8-41ab-b51a-e73061fe18ab)

**Comment by cristiangavilan** [comment]
Excelente Mariano! 
Muchas gracias
