### ISSUE TITLE
Crear Nombre y Logo para el proyecto

### ISSUE THREAD

**Issue by marianom123** [Grupo-7-Pythonisa/final-project#6]
Luego de haber elegido el objetivo del proyecto necesitamos un nombre de marca y un logo que lo represente.

**Comment by cristiangavilan** [comment]
![image](https://github.com/Grupo-7-Pythonisa/final-project/assets/18169782/9970bd46-ccc1-4f04-a3d9-68dcf71a7429)

**Comment by daribethleal** [comment]
![Image](https://github.com/Grupo-7-Pythonisa/final-project/assets/132319484/bbe91c43-6b6f-4782-90aa-880f5b642456)

**Comment by marianom123** [comment]
El nombre de la marca propuesto es: PYTHONISA STORE
